title: My Talks and Meetups
short_title: Dive into my latest talks and meetup moments—where ideas spark and connections grow! 🚀📸
email: shubhendushubham98@gmail.com
description: Showcasing my conference talks, meetups, and community contributions
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sivolko.github.io" # your GitHub Pages URL
github_username: sivolko

# Build settings
plugins:
  - jekyll-feed

# Collections
collections:
  talks:
    output: true
    permalink: /talks/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
  - scope:
      path: ""
    values:
      layout: "default"

# Custom variables
future: true  # Allow future dated posts
show_drafts: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
